version: '3'

networks:
  proxy:
    external: true
  hypertube_network:
    external: false

services:

  postgres:
    image: postgres:10.3
    networks:
      - hypertube_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  hypertubeapi:
    build:
      context: ./backend_api
    environment:
      RAILS_ENV: production
      SIGNUP_REDIRECT_URL: http://192.168.99.100:3000
      DEVISE_SECRET_KEY: f43b6591c23441cb247edc0c3a0f4372e1c56a9e85db26be9aed687fdb2ed919d0f4fad63c6e9753a99194ffc5fde756ce595350cb4bbcbadfe0b3d820df7120
      SECRET_KEY_BASE: b2c9b3355c83d4ccd536fdc50f04293d6a43ef332ff6383fcb11158281d3e1a6c24c0d4904d82062cde8d531f74cc98c5ab75f9cfa637cb4cd5b4d943161afc7
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    labels:
      - traefik.backend=hypertubeapi
      - traefik.frontend.rule=Host:hypertubeapi.tpayet.com
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - proxy
      - hypertube_network

  streamingapi:
    build:
      context: ./torrent_stream_api
    environment:
      HYPERTUBE_DOWNLOAD_PATH: /app/data
      HYPERTUBE_STREAMING_URL: streamingapi.tpayet.com
      HYPERTUBE_VIDEO_API: hypertubeapi/videos

    command: node stream.js
    ports:
      - "5555:5555"
    labels:
      - traefik.backend=streamingapi
      - traefik.frontend.rule=Host:streamingapi.tpayet.com
      - traefik.docker.network=proxy
      - traefik.port=5555
    networks:
      - proxy
