version: '3'

networks:
  proxy:
    external: true
  hypertube_network:
    external: false

volumes:
  users_avatar:
    driver: local

services:

  postgres:
    image: postgres:10.3
    networks:
      - hypertube_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  hypertubeapi:
    build:
      context: ./backend_api
    environment:
      RAILS_ENV: development
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    labels:
      - traefik.backend=hypertubeapi
      - traefik.frontend.rule=Host:hypertubeapi
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - proxy
      - hypertube_network
    volumes:
      - users_avatar:/app/public/system/users
    env_file: backend_api/.env

  streamingapi:
    build:
      context: ./torrent_stream_api
    environment:
      HYPERTUBE_DOWNLOAD_PATH: /app/data
      HYPERTUBE_STREAMING_URL: streamingapi
      HYPERTUBE_VIDEO_API: hypertubeapi

    command: node stream.js
    ports:
      - "5555:5555"
    labels:
      - traefik.backend=streamingapi
      - traefik.frontend.rule=Host:streamingapi
      - traefik.docker.network=proxy
      - traefik.port=5555
    networks:
      - proxy
    env_file: torrent_stream_api/.env
