export const apiDomain = 'https://hypertubeapi.tpayet.com/'
export const signUpUrl = apiDomain + 'auth/'
export const signInUrl = apiDomain + 'auth/sign_in'
export const userUrl = apiDomain + 'users/'
export const searchUrl = apiDomain + 'search?query=:keyword'
