export const apiDomain = 'https://hypertubeapi.tpayet.com/'
// export const apiDomain = 'http://e2r9p1:3000/'
export const backApi = 'http://localhost:5555/'
export const signUpUrl = apiDomain + 'auth/'
export const signInUrl = apiDomain + 'auth/sign_in'
export const forgotPswd = apiDomain + 'auth/password'
export const videoUrl = apiDomain + 'videos/'
export const commentsUrl = apiDomain + 'comments/'
export const userUrl = apiDomain + 'users/'
export const searchUrl = 'http://localhost:5555/search/:keyword'
// export const searchUrl = apiDomain + 'search?query=:keyword'
